# Configuration for semantic-release
branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"

preset: "conventionalcommits"

presetConfig:
  types:
    - type: "feat"
      section: "✨ Features"
    - type: "fix"
      section: "🐛 Bug Fixes"
    - type: "docs"
      section: "📚 Documentation"
    - type: "style"
      section: "💎 Styles"
    - type: "refactor"
      section: "♻️ Code Refactoring"
    - type: "perf"
      section: "⚡ Performance Improvements"
    - type: "test"
      section: "✅ Tests"
    - type: "chore"
      section: "🔧 Chores"
    - type: "ci"
      section: "👷 CI/CD"

releaseRules:
  - type: "feat"
    release: "minor"
  - type: "fix"
    release: "patch"
  - type: "perf"
    release: "patch"
  - type: "docs"
    release: false
  - type: "style"
    release: false
  - type: "refactor"
    release: false
  - type: "test"
    release: false
  - type: "chore"
    release: false
  - type: "ci"
    release: false

changelog:
  changelogFile: "CHANGELOG.md"

github:
  successComment: false
  failComment: false
  releasedLabels: false
