name: Cleanup Caches (TEMPORARY - DELETES ALL)

on:
  schedule:
    - cron: '0 2 * * SUN' # Run every Sunday at 2 AM UTC
  workflow_dispatch: {}   # Allow manual trigger

permissions:
  actions: write

jobs:
  cleanup-caches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete ALL caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching all repository caches to delete them..."
          cache_ids_to_delete=$(gh api --paginate "repos/${{ github.repository }}/actions/caches" | jq '.actions_caches[] | .id')

          if [ -z "$cache_ids_to_delete" ]; then
            echo "No caches found to delete."
            exit 0
          fi

          echo "The following cache IDs will be deleted:"
          echo "$cache_ids_to_delete"

          # Delete each cache by its ID
          echo "$cache_ids_to_delete" | while read -r cache_id; do
            echo "Deleting cache with ID: ${cache_id}"
            gh api "repos/${{ github.repository }}/actions/caches/${cache_id}" -X DELETE --silent || echo "Could not delete cache ${cache_id}. It might have already been removed."
            sleep 0.2 # Small delay to avoid hitting API rate limits
          done

          echo "All existing caches should now be deleted."
