name: Build Flatpak Package (Simple) - DISABLED

on:
  workflow_dispatch:

permissions:
  contents: read         # Needed to checkout code
  actions: read         # Needed to read workflow artifacts

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder python3-pip python3-setuptools
        
    - name: Setup Flatpak system-wide
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk//23.08
        
    - name: Create build directory
      run: |
        mkdir -p build/flatpak
        
    - name: Copy Flatpak files
      run: |
        cp flatpak/org.securebits.bashscriptmaker.simple.yml build/flatpak/org.securebits.bashscriptmaker.yml
        cp flatpak/org.securebits.bashscriptmaker.appdata.xml build/flatpak/
        
    - name: Create Desktop file
      run: |
        cat > build/flatpak/org.securebits.bashscriptmaker.desktop << 'EOF'
        [Desktop Entry]
        Name=Bash-Script-Maker
        Comment=Ein GUI-Programm zur Erstellung von Bash-Scripts
        Exec=bash-script-maker
        Icon=org.securebits.bashscriptmaker
        Terminal=false
        Type=Application
        Categories=Development;Utility;
        Keywords=bash;script;editor;generator;
        StartupWMClass=bash-script-maker
        EOF
        
    - name: Copy icon
      run: |
        mkdir -p build/flatpak/icons/hicolor/scalable/apps
        cp assets/bash-script-maker.svg build/flatpak/icons/hicolor/scalable/apps/org.securebits.bashscriptmaker.svg
        
    - name: Copy Python modules
      run: |
        cp bash_script_maker.py build/flatpak/
        cp syntax_highlighter.py build/flatpak/
        cp localization.py build/flatpak/
        cp custom_dialogs.py build/flatpak/
        cp assets.py build/flatpak/
        
    - name: Create setup.py
      run: |
        cat > build/flatpak/setup.py << 'EOF'
        #!/usr/bin/env python3
        from setuptools import setup

        setup(
            name="bash-script-maker",
            version="1.1.0",
            py_modules=["bash_script_maker", "syntax_highlighter", "localization", "custom_dialogs", "assets"],
            entry_points={
                "console_scripts": [
                    "bash-script-maker=bash_script_maker:main",
                ],
            },
            install_requires=[
                "ttkbootstrap>=1.10.1",
                "pygments>=2.15.1",
            ],
        )
        EOF
        
    - name: Build Flatpak package
      run: |
        cd build/flatpak
        sudo flatpak-builder --repo=repo --force-clean build org.securebits.bashscriptmaker.yml
        
    - name: Create Flatpak bundle
      run: |
        cd build/flatpak
        flatpak build-bundle repo bash-script-maker.flatpak org.securebits.bashscriptmaker
        
    - name: Upload Flatpak bundle
      uses: actions/upload-artifact@v4
      with:
        name: bash-script-maker-flatpak
        path: build/flatpak/bash-script-maker.flatpak
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/flatpak/bash-script-maker.flatpak
        body: |
          ## Flatpak Package
          
          ### Installation
          ```bash
          flatpak install bash-script-maker.flatpak
          ```
          
          ### Verwendung
          ```bash
          flatpak run org.securebits.bashscriptmaker
          ```
          
          ### Features
          - Vollständig sandboxed
          - Automatische Updates
          - Desktop-Integration
          - Keine System-Abhängigkeiten
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
