name: Build Flatpak

# Trigger only when a new release is published
on:
  release:
    types: [published]

jobs:
  build-flatpak:
    name: Build Flatpak Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version from file
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Set up Flatpak builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Cache Flatpak builder dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/flatpak-builder
          key: ${{ runner.os }}-flatpak-builder-${{ hashFiles('build/flatpak/**.yml') }}
          restore-keys: |
            ${{ runner.os }}-flatpak-builder-

      - name: Create build directory and copy files
        run: |
          mkdir -p build/flatpak
          cp flatpak/org.securebits.bashscriptmaker.yml build/flatpak/
          cp flatpak/org.securebits.bashscriptmaker.appdata.xml build/flatpak/
          cp bash_script_maker_flatpak.py build/flatpak/

      - name: Build Flatpak
        run: |
          cd build/flatpak
          flatpak-builder --user --install-deps-from=flathub --force-clean --share=network --share=ipc --share=session-bus build-dir org.securebits.bashscriptmaker.yml

      - name: Create Flatpak Bundle
        run: |
          cd build/flatpak
          flatpak build-bundle repo bash-script-maker.flatpak org.securebits.bashscriptmaker

      - name: Rename Bundle with Version
        run: |
          mv build/flatpak/bash-script-maker.flatpak BashScriptMaker-${{ steps.version.outputs.VERSION }}.flatpak

      - name: Upload Flatpak Bundle as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle
          path: BashScriptMaker-${{ steps.version.outputs.VERSION }}.flatpak
          retention-days: 7