name: Build Flatpak

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read         # Needed to checkout code
  actions: read         # Needed to read workflow artifacts

jobs:
  build-flatpak:
    name: Build Flatpak Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version from file
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Set up Flatpak builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Clear Flatpak cache
        run: |
          rm -rf ~/.cache/flatpak-builder || true

      - name: Create build directory and files
        run: |
          mkdir -p build/flatpak
          cp bash_script_maker_flatpak.py build/flatpak/
          cp flatpak/org.securebits.bashscriptmaker.appdata.xml build/flatpak/
          
          # Create the correct manifest
          cat > build/flatpak/org.securebits.bashscriptmaker.yml << 'EOF'
          app-id: org.securebits.bashscriptmaker
          runtime: org.freedesktop.Platform
          runtime-version: '23.08'
          sdk: org.freedesktop.Sdk
          command: bash-script-maker
          finish-args:
            - --share=ipc
            - --socket=wayland
            - --socket=x11
            - --socket=pulseaudio
            - --device=dri
            - --filesystem=home
            - --filesystem=host
            - --talk-name=org.freedesktop.Notifications
          modules:
            - name: bash-script-maker
              buildsystem: simple
              build-commands:
                - mkdir -p /app/bin
                - cp bash_script_maker_flatpak.py /app/bin/bash-script-maker
                - chmod +x /app/bin/bash-script-maker
              sources:
                - type: dir
                  path: .
          EOF

      - name: Build Flatpak
        run: |
          cd build/flatpak
          flatpak-builder --user --install-deps-from=flathub --force-clean --repo=repo build-dir org.securebits.bashscriptmaker.yml

      - name: Create Flatpak Bundle
        run: |
          cd build/flatpak
          flatpak build-bundle repo bash-script-maker.flatpak org.securebits.bashscriptmaker

      - name: Rename Bundle with Version
        run: |
          mv build/flatpak/bash-script-maker.flatpak BashScriptMaker-${{ steps.version.outputs.VERSION }}.flatpak

      - name: Upload Flatpak Bundle as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle
          path: BashScriptMaker-${{ steps.version.outputs.VERSION }}.flatpak
          retention-days: 7