name: Build Flatpak Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder python3-pip python3-setuptools
        
    - name: Setup Flatpak
      run: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install -y flathub org.freedesktop.Platform//23.08
        flatpak install -y flathub org.freedesktop.Sdk//23.08
        
    - name: Build Flatpak package
      run: |
        chmod +x build_flatpak.sh
        ./build_flatpak.sh
        
    - name: Upload Flatpak bundle
      uses: actions/upload-artifact@v4
      with:
        name: bash-script-maker-flatpak
        path: build/flatpak/bash-script-maker.flatpak
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/flatpak/bash-script-maker.flatpak
        body: |
          ## Flatpak Package
          
          ### Installation
          ```bash
          flatpak install bash-script-maker.flatpak
          ```
          
          ### Verwendung
          ```bash
          flatpak run org.securebits.bashscriptmaker
          ```
          
          ### Features
          - Vollständig sandboxed
          - Automatische Updates
          - Desktop-Integration
          - Keine System-Abhängigkeiten
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
